version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app  # ローカルのfrontendディレクトリをコンテナの/appにマウント

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app  # ローカルのbackendディレクトリをコンテナの/appにマウント
